### ISSUE TITLE
No spaces when more than 60 seconds, like "1min 10s"

### ISSUE THREAD

**Issue by lisphilar** [takelushi/jupyter-autotime#9]
作成ありがとうございます！
Google Colabで使ってみました。

少し気になったのですが、1分未満の場合は`1 s`のように数字と単位の間に空白が表示されるのに対し、1分以上の場合は`1min 10s`のように数字と単位の間から空白がなくなるようです。
https://gist.github.com/lisphilar/fff9f3ca41e1fbdb1bf2865e2d7f5f05

仕様でしたら申し訳ありませんが、ご検討のほどよろしくお願い致します。

**Comment by takelushi** [comment]
@lisphilar 
issue ありがとうございます！！

>1分未満の場合は1 sのように数字と単位の間に空白が表示されるのに対し、1分以上の場合は1min 10sのように数字と単位の間から空白がなくなる

僕としても気にくわないので、修正を検討します！
修正の方針としては以下の通りで考えています。

* 数値と単位の間には必ず半角スペースを入れて表示する
   * OK `1 s` `1 min 10 s`
   * NG `1s` `1min 1s` `1 min1 s`
* 時間のフォーマット関数を上書き可能とする

   ```py
   import datetime
   
   def my_format_time(delta: datetime.delta) -> str:
       # implement here
   autotime.format_time = my_format_time
   ```

* 書式の変更を可能とする
   * e.g. `autotime.RUNNING_FORMAT = '[実行中] ${time} , ${start} ~ ${end}'`
   * e.g. `autotime.FINISHED_FORMAT = '[完了] ${time} , ${start} ~ ${end}'`

**Comment by takelushi** [comment]
v1.0.4 コードについてのメモ

経過時間の書式は `IPython.core.magics.execution._format_time` に任せている。  
該当行
https://github.com/takelushi/jupyter-autotime/blob/main/autotime/__init__.py#L34

_format_time メソッド
https://github.com/ipython/ipython/blob/master/IPython/core/magics/execution.py#L1465

**Comment by takelushi** [comment]
仮実装
![image](https://user-images.githubusercontent.com/17586728/101726627-417cdd00-3af6-11eb-9891-4cfbe3d8be81.png)

**Comment by takelushi** [comment]
@lisphilar 
本 issue のご要望を取り入れたリリースをしました！
https://github.com/takelushi/jupyter-autotime/releases/tag/v1.1.0

パッケージの更新をお願いします。
`pip install -U jupyter-autotime`
`!pip install -U jupyter-autotime`



いかがでしょうか？問題なければクローズさせていただきます 👾

**Comment by lisphilar** [comment]
@takelushi ,
早速ありがとうございます！！！
Google colabでも動作しました！
https://gist.github.com/lisphilar/3bfff768275261c6f1c8db373b2e8ca8

クローズいただいて問題ございません。
また何かあればご報告致します。
